services:
  site:
    image: sitenext
    ports:
      - "5000:3000"
  api:
    image: api
    ports:
      - "5294:8080"
      - "7145:8081"
  sgbd:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Senh@123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: dbdata
        target: /var/opt/mssql
volumes:
  dbdata:
    driver: local
